name: cd

on:
  push:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: lint
        uses: ./.github/workflows/actions/lint
        with:
          node-version: 18

  publish-npm:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          registry-url: https://registry.npmjs.org/
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Publish
        uses: mikeal/merge-release@v4.3.0
        with: 
          GITHUB_TOKEN: ${{ secrets.LURD_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
